# Generated by Django 5.1.4 on 2025-01-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finches', '0003_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='toys',
            field=models.ManyToManyField(to='finches.toy'),
        ),
    ]
